[package]
name = "fractal-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
line_drawing = "1.0.0"
rand = "0.8.5"
structopt = "0.3.26"
