[package]
name = "fractal-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
image = "0.25.6"
line_drawing = "1.0.1"
rand = "0.9.2"
